copidingz/hontrip

src/main/java/com/multi/hontrip/user/controller/UserController.java
=> [fix]Home메서드 변경(requestMapping 추가,반환값 변경)

src/main/java/com/multi/hontrip/plan/controller/PlanController.java
=> [ADD] plan_controller에 inset문 추가

src/main/java/com/multi/hontrip/plan/controller/PlanController.java, src/main/java/com/multi/hontrip/user/controller/UserController.java, src/main/webapp/WEB-INF/views/home.jsp
=> [FEAT] planController insert문 수정

src/main/webapp/WEB-INF/web.xml
=> [add] commit test1

src/main/java/com/multi/hontrip/mate/controller/MateController.java
=> [mate][modify] insert 컨트롤러 수정

src/main/java/com/multi/hontrip/mate/controller/MateController.java
=> [mate][feat] insert 컨트롤러 추가

src/main/java/com/multi/hontrip/mate/controller/MateController.java
=> [mate][feat] insert 컨트롤러 추가2

src/main/java/com/multi/hontrip/mate/controller/MateController.java, src/main/java/com/multi/hontrip/mate/dto/MateDTO.java, src/main/resources/common/db.properties, src/main/resources/sql/공용DB계정, src/main/resources/sql/코피딩즈DB_ddl, src/main/resources/sql/코피딩즈insert_ddl, src/main/webapp/WEB-INF/spring/root-context.xml
DB properties, root context 설정 추가 완료
=> [common] [add] DB설정 추가

src/main/resources/sql/공용DB계정
=> [common] [add] db설정 수정

src/main/java/com/multi/hontrip/user/controller/UserController.java, src/main/java/com/multi/hontrip/user/dao/UserDAO.java, src/main/java/com/multi/hontrip/user/dto/WithdrawUserDTO.java, src/main/java/com/multi/hontrip/user/service/KakaoService.java, src/main/java/com/multi/hontrip/user/service/NaverService.java, src/main/java/com/multi/hontrip/user/service/OauthService.java, src/main/java/com/multi/hontrip/user/service/UserService.java, src/main/java/com/multi/hontrip/user/service/UserServiceImpl.java, src/main/resources/mapper/userMapper.xml, src/main/resources/mybatis-config.xml, src/main/resources/sql/코피딩즈DB_ddl, src/main/resources/sql/코피딩즈insert_ddl, src/main/webapp/WEB-INF/spring/tiles.xml, src/main/webapp/WEB-INF/views/layout/layout.jsp
사용자 탈퇴처리 추가
css 경로 수정
mate controller, 레이아웃 적용되도록 수정
db경로부분 수정
=> [user][add&fix] 사용자 탈퇴기능 추가, mate tiles 적용, layout 경로 수정

src/main/java/com/multi/hontrip/mate/config/ChatHandler.java, src/main/java/com/multi/hontrip/mate/config/ChattingHandShakeInterceptor.java, src/main/java/com/multi/hontrip/mate/config/JacksonConfig.java, src/main/java/com/multi/hontrip/mate/config/WebSocketConfig.java, src/main/java/com/multi/hontrip/mate/controller/ChatController.java, src/main/java/com/multi/hontrip/mate/dao/ChatDAO.java, src/main/java/com/multi/hontrip/mate/dto/ChatInfoDTO.java, src/main/java/com/multi/hontrip/mate/dto/ChatMessageDTO.java, src/main/java/com/multi/hontrip/mate/dto/ChatSessionInfoDTO.java, src/main/java/com/multi/hontrip/mate/dto/ChatroomRequestDTO.java, src/main/java/com/multi/hontrip/mate/dto/JoinChatInfo.java, src/main/java/com/multi/hontrip/mate/dto/MessageType.java, src/main/java/com/multi/hontrip/mate/service/ChatService.java, src/main/java/com/multi/hontrip/mate/service/ChatServiceImpl.java, src/main/java/com/multi/hontrip/user/controller/UserController.java, src/main/java/com/multi/hontrip/user/service/NaverService.java, src/main/resources/mapper/chatMapper.xml, src/main/resources/mapper/userMapper.xml, src/main/resources/mybatis-config.xml, src/main/resources/sql/코피딩즈DB_ddl, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/mate/chat-view.jsp, src/main/webapp/WEB-INF/views/mate/chatroom-view.jsp, src/main/webapp/resources/css/chat.css, src/main/webapp/resources/js/chat.js
=> [user][fix] 탈퇴 날라간거 추가 & 채팅 추가

src/main/java/com/multi/hontrip/user/controller/UserController.java, src/main/java/com/multi/hontrip/user/dao/UserDAO.java, src/main/java/com/multi/hontrip/user/dto/UserDTO.java, src/main/java/com/multi/hontrip/user/dto/UserInfoDTO.java, src/main/java/com/multi/hontrip/user/dto/UserInsertDTO.java, src/main/java/com/multi/hontrip/user/service/KakaoService.java, src/main/java/com/multi/hontrip/user/service/NaverService.java, src/main/java/com/multi/hontrip/user/service/UserService.java, src/main/java/com/multi/hontrip/user/service/UserServiceImpl.java, src/main/resources/mapper/userMapper.xml, src/main/resources/properties/user/kakao.properties, src/main/resources/properties/user/naver.properties, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/user/my-page.jsp
- 마이페이지 추가 
- 세션 관련 설정은 aop로 할 예정
=> [user][add] 마이페이지 추가

src/main/java/com/multi/hontrip/record/controller/RecordContorller.java, src/main/java/com/multi/hontrip/record/dao/RecordDAO.java, src/main/java/com/multi/hontrip/record/dto/PostInfoDTO.java, src/main/java/com/multi/hontrip/record/service/RecordService.java, src/main/resources/mapper/recordMapper.xml, src/main/webapp/WEB-INF/views/record/feedlist.jsp
=> [record][add] 공유피드 수정 createPostDTO에서 postInfoDTO로

src/main/java/com/multi/hontrip/mate/controller/MateController.java, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_insert.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp, src/main/webapp/resources/js/mate.js
=> [mate][fix] 동행인 게시판 로그인 전후 인서트 셀렉트 변경

src/main/webapp/WEB-INF/views/record/mylist.jsp
=> [record][hofix] 공유피드 getmapping수정

pom.xml, src/main/java/com/multi/hontrip/common/CustomErrorAdvice.java, src/main/java/com/multi/hontrip/common/RequiredSessionCheck.java, src/main/java/com/multi/hontrip/common/SessionCheckAdvice.java, src/main/java/com/multi/hontrip/exception/SessionExpiredException.java, src/main/java/com/multi/hontrip/user/controller/UserController.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/user/signin-view.jsp
- aop로 세션 체크 추가
- @RequiredSessionCheck(어노테이션을 붙이면 session을 체크함)
- 추후에 경로도 저장했다 로그인 완료하면 보내주는 기능도 좋을 것 같음
- aop 버전 1.6.~ 에서 1.9.2로 변경
- 버전이 너무 낮아 어노테이션(@Aspect)을 쓸 수 없어 변경
- AspectJ Weaver도 추가
=> [user][add] 세션 체크 aop 적용

src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/layout/header.jsp, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/layout/user_header.jsp, src/main/webapp/WEB-INF/views/mate/chatroom-view.jsp, src/main/webapp/WEB-INF/views/user/my-page.jsp, src/main/webapp/resources/css/user.css
- 홈화면 메뉴 오른쪽 상단에 아이콘으로 뺌
- 회원정보 보여주는 페이지 만듬
=> [user][add] 회원정보보는 기능 추가, 상세구현은 아직 안함

src/main/java/com/multi/hontrip/user/service/KakaoService.java, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/user/my-page.jsp, src/main/webapp/resources/js/user.js
- 카카오 필수항목 동의 안하면 경고창 표시
- 동의 안하고 회원 가입시 에러 처리
=> [user][fix] 회원가입 및 정보 표시 변경

src/main/java/com/multi/hontrip/record/controller/CommentController.java, src/main/webapp/WEB-INF/views/layout/header.jsp, src/main/webapp/WEB-INF/views/layout/user_header.jsp, src/main/webapp/WEB-INF/views/record/createpost.jsp, src/main/webapp/WEB-INF/views/record/postinfo.jsp
=> [record][add] 댓글 css추가

src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp, src/main/webapp/resources/js/mate.js
=> [mate][fix] 상세게시판 유저아이디 수정

src/main/java/com/multi/hontrip/mate/alarm/AlarmController.java, src/main/java/com/multi/hontrip/mate/alarm/AlarmServiceImpl.java, src/main/java/com/multi/hontrip/mate/dao/AlarmDAO.java, src/main/resources/mapper/mateMapper.xml, src/main/resources/properties/user/naver.properties, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/mate/mate_application_alarm.jsp, src/main/webapp/resources/js/mate.js
=> [mate][fix] 알람 알러트 수정

src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp
=> [mate] 오류 해결

src/main/java/com/multi/hontrip/record/dto/CreatePostDTO.java, src/main/java/com/multi/hontrip/record/dto/PostInfoDTO.java, src/main/resources/mapper/recordMapper.xml, src/main/webapp/WEB-INF/views/record/createpost.jsp, src/main/webapp/WEB-INF/views/record/postinfo.jsp
- 여행기간추가 CreatePostDTO, PostInfoDTO 데이터 '추가/삭제' 
- 상세페이지 '수정/삭제' 버튼추가
-  댓글 '작성/수정' '날짜/버튼' 추가
=> [record][add] 우선 여행기간 추가했습니다

src/main/java/com/multi/hontrip/record/controller/CommentController.java, src/main/java/com/multi/hontrip/record/controller/RecordContorller.java, src/main/resources/mapper/recordMapper.xml, src/main/webapp/WEB-INF/views/record/createpost.jsp, src/main/webapp/WEB-INF/views/record/updatepost.jsp
=> [record][add] 게시물작성폼 view 수정, 게시물수정폼 tiles적용, 수정 항목 추가

src/main/java/com/multi/hontrip/record/controller/RecordContorller.java, src/main/webapp/WEB-INF/views/record/feedlist.jsp, src/main/webapp/WEB-INF/views/record/list_mylocation_click.jsp, src/main/webapp/WEB-INF/views/record/list_mylocation_dropdown.jsp, src/main/webapp/WEB-INF/views/record/mylist.jsp, src/main/webapp/resources/css/record.css
=> [record][fix] 드롭다운 오류 수정, 공유피드 CSS 적용, jsp파일 코드 정렬

src/main/java/com/multi/hontrip/record/controller/RecordContorller.java
=> [record][fix] test용 sysout 코드 삭제

src/main/java/com/multi/hontrip/record/controller/RecordContorller.java, src/main/java/com/multi/hontrip/record/dao/PostLikeDAO.java, src/main/java/com/multi/hontrip/record/dto/PostLikeDTO.java, src/main/java/com/multi/hontrip/record/service/PostLikeService.java, src/main/resources/mapper/recordMapper.xml, src/main/resources/mybatis-config.xml, src/main/webapp/WEB-INF/views/record/postinfo.jsp
=> [record][add] 게시물 좋아요 insert기능 추가 mybatis postLikeDTO추가

src/main/java/com/multi/hontrip/plan/controller/FlightController.java, src/main/java/com/multi/hontrip/plan/controller/PlanController.java, src/main/java/com/multi/hontrip/plan/controller/SpotController.java, src/main/java/com/multi/hontrip/plan/dao/PlanDAO.java, src/main/java/com/multi/hontrip/plan/dto/PlanDTO.java, src/main/java/com/multi/hontrip/plan/service/PlanService.java, src/main/java/com/multi/hontrip/plan/service/PlanServiceImpl.java, src/main/resources/mapper/planMapper.xml, src/main/resources/sql/코피딩즈ddl, src/main/webapp/WEB-INF/views/plan/detail.jsp, src/main/webapp/WEB-INF/views/plan/edit.jsp, src/main/webapp/WEB-INF/views/plan/emergency_facility_filter_list.jsp, src/main/webapp/WEB-INF/views/plan/emergency_facility_list.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_form.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_list.jsp, src/main/webapp/WEB-INF/views/plan/list.jsp, src/main/webapp/WEB-INF/views/plan/safety_result.jsp, src/main/webapp/WEB-INF/views/plan/safety_search.jsp, src/main/webapp/WEB-INF/views/plan/spot/detail.jsp, src/main/webapp/WEB-INF/views/plan/spot/search_form.jsp, src/main/webapp/WEB-INF/views/plan/spot/search_list.jsp, src/main/webapp/WEB-INF/views/plan/spot/search_list_for_plan.jsp
일정 수정
- 일정-일차별 여행지 추가 후 삭제도 가능하게 했습니다.
- plan 테이블 컬럼명 id에서 planId로 변경하여 ddl 수정했습니다.
=> [plan][feat&fix] 일정-일차별 추가한 여행지 삭제 기능 구현, plan 테이블 컬럼명 수정

src/main/java/com/multi/hontrip/user/controller/UserController.java, src/main/java/com/multi/hontrip/user/dto/MyRecordDTO.java, src/main/java/com/multi/hontrip/user/service/MyPageService.java, src/main/webapp/WEB-INF/views/user/my-page/my-record-page.jsp, src/main/webapp/resources/css/user.css, src/main/webapp/resources/js/user.js
- 내 여행기록 페이지 css 및 페이징 수정 
- 선택 필드 추가
=> [user][fix] 마이페이지 페이징 및 기타 수정

src/main/webapp/WEB-INF/views/layout/header.jsp, src/main/webapp/WEB-INF/views/layout/user_header.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp
1. 알람->알림 변경
2. 상세게시판 생성날짜부분 위치 변경
=> [mate][fix] 알람->알림 변경, 상세게시판 생성날짜부분 위치 변경

src/main/java/com/multi/hontrip/plan/controller/PlanController.java, src/main/java/com/multi/hontrip/plan/service/PlanService.java, src/main/java/com/multi/hontrip/plan/service/PlanServiceImpl.java, src/main/webapp/WEB-INF/views/plan/edit.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_list.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_list_for_plan.jsp
일정 항공권 삭제 기능 추가했습니다.
덧붙여 여행 범위가 국내로 한정되어 있다 보니 항공권 추가는 일차가 크게 중요하지 않을 것 같아서
dayOrder를 구분하지 않고 모두 1로 설정해 추가되게 했습니다.
=> [plan][feat] 일정 항공권 삭제 구현

src/main/java/com/multi/hontrip/record/controller/RecordContorller.java, src/main/java/com/multi/hontrip/record/dao/RecordDAO.java, src/main/java/com/multi/hontrip/record/service/RecordService.java, src/main/resources/mapper/recordMapper.xml, src/main/webapp/WEB-INF/views/record/feedlist.jsp, src/main/webapp/WEB-INF/views/record/feedlist_dropdown.jsp, src/main/webapp/WEB-INF/views/record/mylist.jsp, src/main/webapp/resources/css/record.css
=> [record][add] 공유피드 드롭다운(권역별) 기능  추가

src/main/java/com/multi/hontrip/mate/controller/MateController.java, src/main/java/com/multi/hontrip/mate/dao/MateDAO.java, src/main/java/com/multi/hontrip/mate/dto/MateBoardListDTO.java, src/main/java/com/multi/hontrip/mate/dto/MatePageDTO.java, src/main/resources/mapper/mateMapper.xml, src/main/webapp/WEB-INF/views/mate/bbs_list.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp, src/main/webapp/resources/js/mate.js, src/main/webapp/resources/js/pagination.js
- 리스트 게시물 부분/상세 게시판에 조회수 표시
- 리스트부분 조회수 순으로 검색하기 기능 추가
- 댓글 수정/삭제 안되었던 부분 수정
- 댓글 세션 부분 수정
=> [mate]리스트부분에 조회수 표시,조회수 순으로 검색하기 기능 추가,댓글 수정/삭제 안되었던 부분 수정,댓글 세션 부분 수정

src/main/webapp/WEB-INF/views/mate/bbs_list.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp, src/main/webapp/resources/css/mate_list.css, src/main/webapp/resources/js/mate.js, src/main/webapp/resources/js/pagination.js
=> [mate]리스트,댓글 부분 css완료

src/main/java/com/multi/hontrip/user/controller/MyPageController.java, src/main/java/com/multi/hontrip/user/dao/MyPageDAO.java, src/main/java/com/multi/hontrip/user/dao/MyPageDAOImple.java, src/main/java/com/multi/hontrip/user/dto/MyRecordDTO.java, src/main/java/com/multi/hontrip/user/dto/PageDTO.java, src/main/java/com/multi/hontrip/user/service/MyPageService.java, src/main/java/com/multi/hontrip/user/service/MyPageServiceImpl.java, src/main/resources/mapper/myPageMapper.xml, src/main/resources/mybatis-config.xml, src/main/webapp/WEB-INF/views/error/404.jsp, src/main/webapp/WEB-INF/views/error/500.jsp, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/layout/left-side.jsp, src/main/webapp/WEB-INF/views/user/my-page/my-record-page.jsp, src/main/webapp/resources/css/user.css, src/main/webapp/resources/js/user.js, src/test/java/com/multi/hontrip/user/dto/PageDTOTest.java
=> [user][add&fix] 다중선택 구헌 & 페이징 일부 수정

src/main/java/com/multi/hontrip/user/dto/MyCitiesDTO.java
=> [user][add] 누락된 dto 추가

src/main/java/com/multi/hontrip/mate/controller/AlarmController.java, src/main/java/com/multi/hontrip/mate/dao/ChatDAO.java, src/main/java/com/multi/hontrip/mate/dto/ChatMessageDTO.java, src/main/java/com/multi/hontrip/mate/dto/ChatroomListDTO.java, src/main/resources/mapper/chatMapper.xml, src/main/webapp/WEB-INF/views/layout/header.jsp, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/layout/nav.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_insert.jsp, src/main/webapp/WEB-INF/views/mate/mate_board_update.jsp, src/main/webapp/resources/css/alarm.css, src/main/webapp/resources/css/chat.css, src/main/webapp/resources/css/mate.css
1. 채팅 css
2. 동행인 게시판 인서트 업데이트 수정
=> [mate][fix & add] 채팅 css, 동행인 게시판 인서트 업데이트 수정

src/main/java/com/multi/hontrip/plan/api/AccommodationApi.java, src/main/webapp/WEB-INF/spring/tiles.xml, src/main/webapp/WEB-INF/views/plan/accommodation/list.jsp, src/main/webapp/WEB-INF/views/plan/edit.jsp, src/main/webapp/WEB-INF/views/plan/emergency_facility/filter_list.jsp, src/main/webapp/WEB-INF/views/plan/emergency_facility/list.jsp, src/main/webapp/WEB-INF/views/plan/safety_result.jsp, src/main/webapp/WEB-INF/views/plan/safety_search.jsp
=> 여행계획 edit.jsp 모달 추가

src/main/webapp/WEB-INF/views/user/my-page/my-record-page.jsp, src/main/webapp/resources/css/user.css, src/main/webapp/resources/js/user.js
=> [user][fix] 마이레코드페이지 필터 로직 변경

src/main/java/com/multi/hontrip/plan/controller/PlanController.java, src/main/webapp/WEB-INF/views/plan/accommodation/accommodation_search_list_for_plan.jsp, src/main/webapp/WEB-INF/views/plan/edit.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_form.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_form_for_plan.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_list_for_plan.jsp, src/main/webapp/WEB-INF/views/plan/list.jsp, src/main/webapp/WEB-INF/views/plan/spot/search_list_for_plan.jsp, src/main/webapp/resources/css/plan.css
- plan/edit.jsp, plan/list.jsp css 수정
- plan/list.jsp 일정 삭제 confirm 대화상자 추가
=> [plan][fix&add] 일정 상세 및 목록 css 수정, 일정 삭제 confirm 대화상자 추가

src/main/java/com/multi/hontrip/user/controller/MyPageController.java, src/main/webapp/WEB-INF/views/user/my-page/my-record-page.jsp, src/main/webapp/resources/js/user.js
=> [user][fix] 선택 삭제 컨트롤러 구현

src/main/webapp/WEB-INF/views/plan/edit.jsp
- 여행지 삭제 후 남은 여행지 없는 div 숨김 처리
- 덜 교체한 css 수정
=> [plan][fix] 여행지 삭제 후 남은 여행지 없는 div 숨김 처리

src/main/resources/mapper/recordMapper.xml
=> Feature/pys record13 sql문 수정

src/main/java/com/multi/hontrip/mate/controller/MateController.java, src/main/java/com/multi/hontrip/mate/dto/MateBoardListDTO.java, src/main/java/com/multi/hontrip/mate/service/MateService.java, src/main/java/com/multi/hontrip/mate/service/MateServiceImpl.java, src/main/resources/mapper/mateMapper.xml, src/main/resources/sql/코피딩즈ddl, src/main/webapp/WEB-INF/views/layout/header.jsp, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/mate/bbs_list.jsp, src/main/webapp/resources/css/chat.css, src/main/webapp/resources/css/mate_list.css, src/main/webapp/resources/js/pagination.js
=> 동행인 게시판 리스트에 나이 나타내는 로직 추가]

src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp
=> [mate]댓글 부분 오타 수정

src/main/java/com/multi/hontrip/mate/controller/ChatController.java, src/main/java/com/multi/hontrip/mate/dto/ChatroomListDTO.java, src/main/resources/mapper/chatMapper.xml, src/main/webapp/WEB-INF/views/layout/header.jsp, src/main/webapp/WEB-INF/views/layout/layout.jsp, src/main/webapp/WEB-INF/views/mate/bbs_list.jsp, src/main/webapp/resources/css/chat.css, src/main/webapp/resources/css/mate_list.css
- 동행인 리스트 css깨지는 문제 해결
- 체팅 목록 마지막으로 보낸 발신자 이름불러오기/시간 불러오기
- 채팅 목록css
=> [mate] 동행인 리스트 css깨지는 문제 해결, 체팅 목록 마지막으로 보낸 발신자 이름불러오기/시간 불러오기, 채팅 목록css

src/main/webapp/WEB-INF/views/plan/emergency_facility/filter_list.jsp
=> [Plan][edit] 응급시설 페이지 수정

src/main/resources/properties/plan/kakaomapApi.properties, src/main/resources/properties/plan/openApi.properties, src/main/resources/properties/user/kakao.properties, src/main/resources/properties/user/naver.properties, src/main/webapp/WEB-INF/views/plan/edit.jsp, src/main/webapp/WEB-INF/views/plan/emergency_facility/filter_list.jsp, src/main/webapp/WEB-INF/views/plan/emergency_facility/list.jsp, src/main/webapp/WEB-INF/views/plan/safety_result.jsp, src/main/webapp/WEB-INF/views/plan/safety_search.jsp
응급시설/안전정보 모달에 적용
>> edit.jsp 전체 적용은 안 됨...
=> 여행계획 로딩써클/검색결과/숙소 깨지는 것 처리

src/main/java/com/multi/hontrip/HomeController.java, src/main/java/com/multi/hontrip/mate/dao/MateDAO.java, src/main/java/com/multi/hontrip/mate/service/MateService.java, src/main/java/com/multi/hontrip/mate/service/MateServiceImpl.java, src/main/resources/mapper/mateMapper.xml, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/mate/bbs_list.jsp, src/main/webapp/resources/css/mate_list.css, src/main/webapp/resources/js/pagination.js
- 홈 화면에 조회수 순으로 목록들 출력되게 수정 
- 새로고침 시 바뀌는거 표시되는 사항들 덜 표시되게 bbs_list와 pagination 내용들 같게 수정
=> [mate] 홈 화면에 인기있는 목록들 출력되게 수정 /bbs_list와 pagination 내용들 같게 수정

src/main/java/com/multi/hontrip/HomeController.java, src/main/java/com/multi/hontrip/plan/controller/FlightController.java, src/main/java/com/multi/hontrip/plan/controller/SpotController.java, src/main/java/com/multi/hontrip/plan/dao/SpotDAO.java, src/main/java/com/multi/hontrip/plan/dao/SpotLikeDAO.java, src/main/java/com/multi/hontrip/plan/dto/SpotInfoDTO.java, src/main/java/com/multi/hontrip/plan/dto/SpotLikeDTO.java, src/main/java/com/multi/hontrip/plan/parser/FlightParser.java, src/main/java/com/multi/hontrip/plan/service/SpotLikeService.java, src/main/java/com/multi/hontrip/plan/service/SpotLikeServiceImpl.java, src/main/java/com/multi/hontrip/plan/service/SpotService.java, src/main/java/com/multi/hontrip/plan/service/SpotServiceImpl.java, src/main/resources/mapper/planMapper.xml, src/main/resources/mapper/spotMapper.xml, src/main/resources/mybatis-config.xml, src/main/resources/sql/코피딩즈ddl, src/main/resources/sql/코피딩즈insert_ddl, src/main/webapp/WEB-INF/views/home.jsp, src/main/webapp/WEB-INF/views/layout/left-side.jsp, src/main/webapp/WEB-INF/views/mate/bbs_list.jsp, src/main/webapp/WEB-INF/views/plan/edit.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_form.jsp, src/main/webapp/WEB-INF/views/plan/flight/search_list.jsp, src/main/webapp/WEB-INF/views/plan/list.jsp, src/main/webapp/WEB-INF/views/plan/spot/detail.jsp, src/main/webapp/WEB-INF/views/plan/spot/search_form.jsp, src/main/webapp/WEB-INF/views/plan/spot/search_list.jsp, src/main/webapp/WEB-INF/views/user/my-page/user-info.jsp, src/main/webapp/resources/css/plan.css
- 여행지 검색 결과 리스트에서 즐겨찾기 추가 및 해제
- 여행지 상세에서 즐겨찾기 추가 및 해제
- 홈 화면에 즐겨찾기 수 상위 10개 여행지 노출
- spot_like 테이블 ddl  추가, insert ddl 추가
=> [plan][feat] 여행지 즐겨찾기 기능 추가

src/main/webapp/WEB-INF/views/record/feedlist.jsp, src/main/webapp/WEB-INF/views/record/feedlist_like.jsp, src/main/webapp/WEB-INF/views/record/feedlist_location_buttons.jsp, src/main/webapp/WEB-INF/views/record/post_list_page2.jsp
=> [record][fix] 코드 정리 및 정렬

src/main/java/com/multi/hontrip/plan/service/PlanServiceImpl.java
여행계획 planservice system.out 찍히는 부분 삭제
=> 여행계획 sys 삭제

src/main/webapp/WEB-INF/views/mate/mate_board_selectOne.jsp, src/main/webapp/resources/js/mate.js
=> [mate] 댓글쪽 오타 수정

src/main/java/com/multi/hontrip/mate/controller/AlarmController.java, src/main/webapp/resources/css/chat.css
=> [mate][fix] 채팅 css 수정
